server: G_PES2UG19CS451_Week9a.o etmain.o
	gcc -o server etmain.o G_PES2UG19CS451_Week9a.o
G_PES2UG19CS451_Week9a.o: G_PES2UG19CS451_Week9a.c et.h
	gcc -c G_PES2UG19CS451_Week9a.c et.h
etmain.o: et.h etmain.c
	gcc -c et.h  etmain.c