server: G_PES2UG19CS451_Week10.o tbtmain.o
	gcc -o server tbtmain.o G_PES2UG19CS451_Week10.o
G_PES2UG19CS451_Week10.o: G_PES2UG19CS451_Week10.c tbt.h
	gcc -c G_PES2UG19CS451_Week10.c tbt.h
tbtmain.o: tbt.h tbtmain.c
	gcc -c tbt.h tbtmain.c